### ISSUE TITLE
你这个开源有点忽悠人

### ISSUE THREAD

**Issue by vanehu** [bbqz007/xw#6]
啥都木有

**Comment by bbqz007** [comment]
do you understand what is open source what is so different with making sence under your chinese logic.

this repo is sorry not a collection for your fork.

you can link the library and dll under a not cm lisence. you also do not need to release your code, because this repo is not under GPL lisence, and i do not have any rely on the problems of the library as well.

this repo has include headers and binaries for programming. demos shows how to use and what  can this library do.

**Comment by bbqz007** [comment]
this repo also has docs. and the doc shows ideas and the purpose of design as well.

**Comment by bbqz007** [comment]
your title say bamboozled.

can you list details?

do you use this software?

do you just want to copy all codes and gain unlimited benefits from others?

do you understand the freedom and the rights?
